version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_estoque
    restart: always
    ports:
      - "4747:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
